### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by Jiveur** [MMM-CalendarExt2/MMM-CalendarExt2#118]
hello, I can't display my calendar, it works with the basic calendar but not with MMM-CalendarExt2, I used the code example, but magic mirror shows me "This site can't be reached", I have the same with MMM-CalendarExt.
For information, I work with a raspberry pi zero W.

**Comment by sdetweil** [comment]
looks like there is a missing dependency, 'valid-url'

**Comment by Jiveur** [comment]
> looks like there is a missing dependency, 'valid-url'

That was this, thank you for help !

**Comment by sdetweil** [comment]
@Jiveur you should keep this open til the author fixes the package.json

**Comment by Jiveur** [comment]
Sorry, i'm new here...

**Comment by klaernie** [comment]
@sdetweil Thanks for your support. Could you help me with the fix? I've not yet understood all there is about javascript packaging.

**Comment by sdetweil** [comment]
@klaernie you need to do npm install valid-url --save

it will update package.json, and then u need to add/commit/push this change to github

npm install reads the list of dependencies in package.json and makes sure they are installed as well

**Comment by risaacson** [comment]
I'll confirm @sdetweil's suggestion as a confirmed fix.

This is required due to https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/4dea3953a2ec7975b17f7621544e724afff94295/node_helper.js#L3

Specifically why you need to require this in your package.json is that it was removed in the Magic Mirror package as of 04/02 via: https://github.com/MichMich/MagicMirror/blob/491f5aa7769a12de7f20f201de0078704c158a8d/CHANGELOG.md
