### ISSUE TITLE
(node:928) UnhandledPromiseRejectionWarning: FetchError: maximum redirect reached at: https://p43-caldav.icloud.com/published/2/blablabla

### ISSUE THREAD

**Issue by Robin-Hol** [MMM-CalendarExt2/MMM-CalendarExt2#163]
Hi there, I updated the module and the MagicMirror2 OS. After that and also before update nothing of the calendars was showing up . Even before update nothing was changed - it came out of the blue.

Error Log:
<img width="1239" alt="Bildschirmfoto 2022-03-03 um 18 50 25" src="https://user-images.githubusercontent.com/100868294/156622720-ecba70bb-827a-4c6d-a9bc-c31b8f7893e9.png">

Can you please help ??

**Comment by klaernie** [comment]
My first guess would be iCloud acting up. That's the reason I use vdirsyncer in my setup, since it uses different APIs to interact with iCloud.

As a first attempt maybe try to generate a new iCloud URL.

**Comment by Robin-Hol** [comment]
no, that did not help. I set up a new calendar (iCloud) with a fresh new link. But it is the same. The whole tool (module) is not showing up on screen. The error should be some where else.

**Comment by Robin-Hol** [comment]
Yes please try this one:
webcal://p65-caldav.icloud.com/published/2/MTMyMzkwMTUxMTMyMzkwMRpOytKCcjtgy1WyZ8HFRe7GAcc5vtcl0eZMyzKzcSfTVlgZprwOQ6eZd0HG-MDqW7QISa6pbJOnLh-blG2WOUA

**Comment by KristjanESPERANTO** [comment]
This calendar works fine for me.

Does the error also occur when you use the following configuration?

```js
    {
      module: "MMM-CalendarExt2",
      config: {
        calendars: [
          {
            url: "webcal://p65-caldav.icloud.com/published/2/MTMyMzkwMTUxMTMyMzkwMRpOytKCcjtgy1WyZ8HFRe7GAcc5vtcl0eZMyzKzcSfTVlgZprwOQ6eZd0HG-MDqW7QISa6pbJOnLh-blG2WOUA"
          }
        ],
        views: [
          {
            mode: "month"
          }
        ],
        scenes: [
          {
            name: "DEFAULT"
          }
        ]
      }
    }
```

**Comment by Robin-Hol** [comment]
No, that actually works fine!

**Comment by Robin-Hol** [comment]
My config code that worked for years is here attached.

I did not make any changes until the calendars just disappeared.

Could you please check ? Is there something to change ?

I also tested the calendar test URL with same config. But same behavior .
>  url: "webcal://p65-caldav.icloud.com/published/2/MTMyMzkwMTUxMTMyMzkwMRpOytKCcjtgy1WyZ8HFRe7GAcc5vtcl0eZMyzKzcSfTVlgZprwOQ6eZd0HG-MDqW7QISa6pbJOnLh-blG2WOUA"

 
_______________________________________________________________________________
Robin Holze • e-mail: ***@***.*** ***@***.***> • web: http://www.robinholze.de <http://www.robinholze.de/>

**Comment by Robin-Hol** [comment]
Here you find my config-snippet:
https://pastebin.pl/view/08c037f3

**Comment by KristjanESPERANTO** [comment]
I took your configuration and replaced all URLs with the one from the test calendar. It works with that:
![Ekrankopio de 2022-03-06 00-01-56](https://user-images.githubusercontent.com/35647502/156902576-a05be5a4-677a-44ef-bdfd-4dcda085a506.png)

Your URLs all start with `https` instead of `webcal`. Your test calendar starts with `webcal`. Can that be the problem?

Which node version are you using? You can check that with  `node -v`.

**Comment by KristjanESPERANTO** [comment]
Someone on the [forum](https://forum.magicmirror.builders/topic/16452/mm-calendar-module-icloud-public-calendar-not-working/7?_=1646560317132) had a similar problem that was solved by resetting the calendar URL:

```
I just unchecked the Public calendar in iCloud and rechecked it again - this changed the link to

webcal://p102-caldav.icloud.com/published/2/xxx
```

**Comment by Robin-Hol** [comment]
Hi, 
Node Version is: v17.6.0
I retested the original config file (https://pastebin.pl/view/08c037f3) with the test calendar and webcal instead of https.
Then I did  this: I just unchecked the Public calendar in iCloud and rechecked it again - this changed theirs part of the link !!! 

Since these changes everything works fine again!

Thank you for your help!!!

**Comment by klaernie** [comment]
I remember doing something similar back when I used iCloud directly - but that totally escaped my mind.

If you still have the old URL could you try a `curl --location --max-redirs 255 https://p43-caldav.icloud.com/published/2/blablabla` (of cause with the proper URL)? It should give an indication of how many redirects iCloud puts you through.
My guess would be that once in a while they redistribute the calendars to new servers, and put up a redirect in the old place. Now after a while a calendar might go through 20 redirects, which would then be refused by `fetch()` because it suspects and endless loop, all the while Apple only migrated that calendar to the 21st host. But that's just a theory - a tech theory. (sorry for that pun)

**Comment by Robin-Hol** [comment]
I actually do not have the old URL anymore. But your explanation sounds absolute realistic to me.
The case could be interesting to other users as well.

Anyway thanks for your help.

**Comment by Robin-Hol** [comment]
Hi,

is there any parameter I can set, to only display TODAYs appointments under „upcoming“ ?? (not tomorrows…)

_______________________________________________________________________________
Robin Holze • e-mail: ***@***.*** ***@***.***> • web: http://www.robinholze.de <http://www.robinholze.de/>

**Comment by klaernie** [comment]
just set `maxDays` to `0`
https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/main/docs/Configuration/Views/current,-upcoming.md
