### ISSUE TITLE
Plus rien

### ISSUE THREAD

**Issue by 1eretoile** [MMM-CalendarExt2/MMM-CalendarExt2#316]
Bonjour depuis quelques jours tout le calendrier ne s'affiche plus sur magic mirror
J'ai rien modifié

**Comment by KristjanESPERANTO** [comment]
Which node version do you have? Check it with `node -v`? Minimum is 18 now.

**Comment by 1eretoile** [comment]
v10.16.0
du coup comment mettre a niveau?

**Comment by klaernie** [comment]
How to update your nodejs depends heavily on what operating system your pi is running. On Debian based systems you should be able to `apt update && apt install nodejs`

**Comment by 1eretoile** [comment]
Voila ce que cela fait
![IMG_20231018_141452](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/assets/138229271/cb0cac20-2d0f-4da9-9760-b1ac32871b20)

Je suis vraiment débutant, j'ai réussi à faire mon magic mirror avec pas mal de recherche et d'aide si tu peut m'aider c'est super sympa

**Comment by klaernie** [comment]
You need to run all `apt` commands with the right of user root - in this case it would suffice to `sudo apt update && sudo apt install nodejs`.
Maybe also copy the output of `cat /etc/os-release`, that would let us know if your debian-based raspberry pi image is fairly up to date, or might need a general update to a newer debian release. I sadly expect the latter, since the last debian release to ship with nodejs 10 was buster, which also carries the name old-old-stable (so there have been two major releases of debian since then)

**Comment by 1eretoile** [comment]
j'ai fait sudo apt update && sudo apt install nodejs


![IMG_20231018_143930](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/assets/138229271/72bd09ef-b8b1-4ee5-8f52-c428db23730b)

copier la sortie de cat /etc/os-release

![IMG_20231018_144306_resized_20231018_024316035](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/assets/138229271/d5c7e65b-d400-40cf-a1c3-8d022125be7f)

**Comment by klaernie** [comment]
In case you are not aware yet: I'd recommend you take a look at regularly updating the entire software on our raspberry, since there will always be bugs in software. You're running raspian 11, and on Oct 10 version 12 "bookworm" was released.  So sooner or later software like MMM-CalendarExt2 or Magic Mirror² might require versions that are only available in this newer release. Any time this happens you can expect people to make a new release, in which this new requirement is stated. And if your system doesn't have the requirements like you system had today, you'll see similar issues again.
