### ISSUE TITLE
Calendar Positioning Issue

### ISSUE THREAD

**Issue by ems522** [MMM-CalendarExt2/MMM-CalendarExt2#351]
I am connecting to a 3rd party calendar of mine, and wanted to do the 'month' view.  Previously, the "fullscreen_bottom" was working, meaning it was loading on my view/scene, however now for some reason it stopped loading.  I can do "fullscreen", "bottom_center", but "fullscreen_bottom" no longer loads.  That being said, it still wasn't exactly what I needed. I want to center the calendar and have it so the entire calendar displays and doesn't cut off anything else.  I currently have Time in top left, weather in top right, and news feed in bottom bar. 

I would like to display the month calendar centered in the screen where I can see everything I need.
Attached is how it looked last when i actually got the "fullscreen_bottom" to display.

here's my config code where im calling the Ext2 module:

```js
{
		module: 'MMM-CalendarExt2',
		config: {
		  rotateInterval: 1000*60,
		  locale: "en-US", 
		  defaultSet: {
			view: {
			  hideOverflow:true,
			}
		  },
		  calendars : [
			{
			  name: "US holiday",
			  icon: "noto-beach-with-umbrella",
			  className: "holiday",
			  url: "http://www.calendarlabs.com/templates/ical/US-Holidays.ics",
			},
	  		{
			  name : "Family Calendar",
			  icon: "noto-spiral-calendar",
			  url: "<Link to my 3rd Party Calendar>",
			  scanInterval: 1000*60*1,
			}
		  ],
		  views: [
			{
			  name: "VIEW1",
			  mode: "daily",
			  timeFormat: "h:mm A", 
			  title: "Upcoming",
			  calendars: ["Family Calendar", "US holiday"],
			  slotCount: 4,
			  position: "top_left",
			},
			{
			  name: "VIEW2",
			  mode: "month",
			  timeFormat: "h:mm A",
			  title: "",
			  calendars: [],
			  //position: "fullscreen_bottom", (this was previously loading, but isn't anymore for some reason)
			  position: "bottom_center",
			},
	                ],
		  scenes: [
			/*{
			  name: "DEFAULT",
			  views:[],
			},*/
			{
			  name: "ONLY_VIEW2",
			  views:["VIEW2"]
			},
			{
			  name: "ONLY_VIEW1",
			  views:["VIEW1"]
			}
		  ],
		},
	  },
```

**Comment by ems522** [comment]
![MagicMirror](https://github.com/user-attachments/assets/9d4c1028-d37f-4830-be33-b7267a6e654c)

**Comment by ems522** [comment]
@klaernie   Sorry to bother you, but any help would be greatly appreciated as this has been driving me crazy ha!

**Comment by KristjanESPERANTO** [comment]
Officially there is no `fullscreen_bottom` position ([see docs](https://docs.magicmirror.builders/modules/configuration.html)). Do you mean `fullscreen_below`?

**Comment by ems522** [comment]
ok so yes i am an idiot i actually just figured that out, my brain was clearly fried yesterday.  But I just saw this example.  How could i put everything on the left, and then put the calendar on the right?

![image](https://github.com/user-attachments/assets/fb08d8e5-a73e-4e19-86be-3e99ea0ad1ca)

**Comment by klaernie** [comment]
Hi @ems522!

please don't repeatedly ping me, this issue is not even one day old, and despite appearance I am not available 24/7 for support - I got a job as well.
Also by default anybody who participated in an issue on GitHub gets notifications, so you can assume Kristian saw your reply. But we all do this in our free time, and sometimes there is not much time for open source work.

Regarding your technical problems: pick one of the magic mirror regions that is one the right side, and make sure you have no other modules on the right side as well. Than you can use CSS to adjust the height and width, if just setting `slotMaxHeight` is not sufficient. And to add borders (or any styling at all please check the docs, you must use CSS to do so). 

Best regards,
Andre

**Comment by ems522** [comment]
My apologies.  Didn’t realize it pinged out, thought it would be more of a notification next time you are in GitHub. Sorry  and thanks for your helpSent from my iPhoneOn Oct 2, 2024, at 11:49 AM, Andre Klärner ***@***.***> wrote:﻿
Hi @ems522!
please don't repeatedly ping me, this issue is not even one day old, and despite appearance I am not available 24/7 for support - I got a job as well.
Also by default anybody who participated in an issue on GitHub gets notifications, so you can assume Kristian saw your reply. But we all do this in our free time, and sometimes there is not much time for open source work.
Regarding your technical problems: pick one of the magic mirror regions that is one the right side, and make sure you have no other modules on the right side as well. Than you can use CSS to adjust the height and width, if just setting slotMaxHeight is not sufficient. And to add borders (or any styling at all please check the docs, you must use CSS to do so).
Best regards,
Andre

**Comment by klaernie** [comment]
Don't worry, you're not even 24h on GitHub ;) Better you learn that lesson from somebody who does not stockpile that emotion and will help you anyway. So feel free to ask when you get stuck!

**Comment by ems522** [comment]
So I found this code online and copied it to the MMM-CalendarExt2.css file, It's very close to what I need however it's overlapping my bottom bar news feed, and is slightly running off the screen to the right:

/* Make the module fullscreen */
.MMM-CalendarExt2 {
  width: 78vw; /* Full width of the viewport */
  height: 75vh; /* Full height of the viewport */
  position: fixed; /* Fixed positioning */
  right: 0; /* Align to the right */
  top: 0;
  left: 10;
  bottom: 100;
  z-index: 9999; /* Ensure it appears on top */

}

/* Optional: Adjust text color and background */
.MMM-CalendarExt2 .your-inner-element {
  color: white; /* Change to your preferred color */
  background-color: rgba(0, 0, 0, 0.7); /* Semi-transparent background */
}

I assume this is 'overriding' the parameters being set within the config.js file for that module call. 
I then went and commented out the code from the .css file and instead went back to config.js and set the position of the VIEW displaying my calendar, to "top_right". (everything else is "top_left" and displaying properly.

I tested and it shows components on left still without issue, however my calendar is way condensed  and also cutting off the bottom bar.




Here is my view config code.  VIEW2 is what is showing the calendar having the issue.

views: [
			{
			  name: "VIEW1",
			  mode: "daily",
			  timeFormat: "h:mm A", 
			  title: "Upcoming",
			  calendars: ["Sinclair FamilyWall", "US holiday"],
			  slotCount: 4,
			  //position: "top_left", default
			  position: "bottom_left",
			},
			{
			  name: "VIEW2",
			  mode: "month",
			  timeFormat: "h:mm A",
			  title: "",
			  calendars: [],
			  position: "top_right", 
			  //position: "fullscreen_below",
			  //position: "bottom_center",
			},
	  
		  ],

and when i do it this way, as you can see the calendar is shrunk and the slots are really small.
![image](https://github.com/user-attachments/assets/09cd7f47-f3a8-40f7-bc98-dd5ade4a63ff)

**Comment by klaernie** [comment]
Indeed the CSS you pasted is overriding the position and ignoring the regions set in config.js. But contrary to the comment they set the width and their to 78% and 75% of the viewport (the browser window). 

Btw, if you want to apply CSS it is preferable to use the custom.css [as described in their docs](https://docs.magicmirror.builders/modules/customcss.html). This makes sure your own CSS does not get removed when you eventually update this module.

Your approach to simple use region `top_right` looks good so far, you probably need to adjust `slotMaxHeight` to something less than the default to fit all onto the screen: https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/main/docs/Configuration/Views/week%2C-month.md. To me it looks like there are just a few pixels below the screen, since the start of November is visible (which is the last row). The calendar right now probably takes up 900 vertical pixels (6*150), and your screen has right around 900 pixels itself. So if you want to ensure that the calendar does not overlap the Newsfeed you need to guess the Newsfeed hight, subtract that from your vertical screen resolution, subtract the calendar title as well, and divide the rest into 6 to get the right slotMaxHeight. Or you just guess until it looks right;)

To get the width right you need to override a bit of Magic Mirror default sizing with CSS:
This is what I do in my setup (which is listed in full in docs/examples):
```css
.region.top.right,
.region.top.left,
.region.top.center {
  min-width: 700px;
}

.region.top.left .CX2 {
  --column-max-width: 700px;
}
```

With that I can use the space on my ultrawide Magic Mirror screen better, you of cause need to find the right value to set the width to. 

One last thing: please lookup how to make code blocks when commenting in GitHub issues - Kristjan and me had to edit your comments to make the code readable, but we can only do that since we are admins of this repo, so it would be nice to format it right from the get go.

**Comment by ems522** [comment]
Sorry, I will use code blocks from now on!  So after a lot of trial and error, I think I have it close to how I want it, for now.  That being said, I made updates to the MMM-CalendarExt2.css.  But you are saying instead of modifying the module specific css to instead utilize the custom css?  Stupid question, but obviously I will rename it from custom.css.sample to just custom.css, but do I simply just move my code from the module css to the custom css and save and it will pick those changes up?  Or is there something I need to update for it to pick up the custom.css file?

**Comment by ems522** [comment]
Ok yea so i copied 
`/*Make the calendar wider*/
.MMM-CalendarExt2{
  width: 79%; /* Adjust width as needed*/
  max-width: 100%; /* Prevent overflow */
  max-height: 1100px; /*Adjust this value to your preferred height */
  /*overflow-y: auto; /*Allows scrolling if content exceeds max-height*/
  position: fixed; /* Keep it in position */
  /*right: 0; /* Align to the right */ 
  left: 20px; 
  top: 0; /*Align to the top */
  z-index: 9999; /* Ensure it appears on top */
  background-color: rgba(0, 0, 0, 0.7); /*Optional: semi-transparent background */
  color: white; /* Optional: text color */
  margin-bottom: 100px; /*Adjust based on height of your bottom bar */
  z-index: 9999;
  border-bottom: 2px solid #ffffff;
}

/* Adjust inner elements if needed */
.MMM-CalendarExt2 .your-inner-element {
  /* Add styles specific to inner elements, if necessary */
}`

and moved it inside root{ of my renamed custom.css file and it looks like it's working!

**Comment by ems522** [comment]
Learning here...slowly but surely!  Now I am trying to figure out how to format slots/events based on text.

So for instance, if my event has the word birthday or Birthday in it, I want to make that event's background color Green, etc...
Is this feasible?

Appreciate your help this far!  Happy weekend!

**Comment by klaernie** [comment]
It is: https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/blob/main/docs/Filtering-and-Sorting.md#transforming
The docs also explain how the event object looks like, and you can set a CSS class, they apply your style to this class in custom.css

**Comment by ems522** [comment]
Got this to work thank you!
