### ISSUE TITLE
Error after PIR wake up

### ISSUE THREAD

**Issue by EMHBooth** [MMM-CalendarExt2/MMM-CalendarExt2#68]
My CalendarExt2 has started behaving strangely.  I have 2 scenes set which rotate, they are both set to show 3 weeks as in picture 1.  When the screen wakes up using PIR-Sensor I got the picture 2 and have to restart the magicmirror.

Any suggestions please?

![0721CD8C-5F56-44C9-AE3D-3C4B31490E7C](https://user-images.githubusercontent.com/49461297/79267971-02639280-7e68-11ea-9c08-86bd8ba9e48e.jpeg)
<img src="https://user-images.githubusercontent.com/49461297/79268033-17d8bc80-7e68-11ea-9147-5d70d7dace08.jpeg" alt="0FF38A4A-D0EE-497C-9499-82453BA74930" style="  -webkit-transform:rotate(180deg);   -moz-transform: rotate(180deg);   -ms-transform: rotate(180deg);   -o-transform: rotate(180deg);   transform: rotate(180deg);">

**Comment by eouia** [comment]
I don't know how your PIR works. Can you send me more details? (configuration) (eouia0819@gmail.com)

**Comment by EMHBooth** [comment]
Hi

I am using MMM-PIR-Sensor with a standard sensor.  It was all working perfectly before the major upgrade to MagicMirror at which point everything stopped working and had to be rebuilt completely.

Thanks

**Comment by klaernie** [comment]
Does this also happen, when you deactivate the PIR sensor?

**Comment by klaernie** [comment]
@EMHBooth could you please post your configuration?

**Comment by EMHBooth** [comment]
[config.txt](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/files/4743021/config.txt)

Config file attached. It is not rotating the scenes at allnie

Sorry for the delay.

Thanks

**Comment by klaernie** [comment]
I don't see anything in the config or PIR code that could cause this. Can you VNC into the Pi when it is off? My only suspicion would be, that when the display is turned off electron somehow changes its behavior and break CX2, but that would be probably noticed by someone else by now. 

Else I would suggest you start MM with devtools enabled, and when it comes up in the broken state dig through the DOM and see what the actual state is. From the pictures alone I cannot tell what visual piece belongs to what. Doesn't help that it's upside down.

**Comment by nitewing76** [comment]
@klaernie ...this might be the same root cause for an issue I'm having with MMM-Pages. Moving from page to page manually works great. But there is a setting in MMM-Pages that, after a defined amount of inactivity, MM will go back to Page 1. But when this happens, MMM-CalendarExt2 does not receive a notification for CALEXT2_SCENE_CHANGE. In other words, CalendarExt2 still thinks in on a different page...so it shows the scene for the page it thinks it is on.  If I am correct, from what I read in MMM-CalendarExt2.js the notification is: _changeSceneByName._  

What is the proper syntax for the payload? ...with this info, the calendar can now know which scene to run.

**Comment by EMHBooth** [comment]
Replaced PIR module with MMM-NewPIR as previous was no-longer supported.
