### ISSUE TITLE
Calendar flickering/jumping all over the place

### ISSUE THREAD

**Issue by mabahj** [MMM-CalendarExt2/MMM-CalendarExt2#74]
Hi,
I just restarted my Pi (has been running for a while) and suddenly the calendar is jumping all over the place. I've narrowed it down to something that happened in 2f786b7. If I checkout a2828f5, then it works (no jumping), but 2f786b7 or master has this jumping issue. It happens both when viewed from my lapttop (Vivaldi, Linux) and on my Pi.

I see there's a lot of divs being created and deleted.

I've reduced my config.js down to this, which contains only MMM-CalendarExt2. 

[jumping-config.js.txt](https://github.com/eouia/MMM-CalendarExt2/files/4577141/jumping-config.js.txt)

For now, I'll just use 2f786b7.

(Thanks for a great plugin!)

**Comment by klaernie** [comment]
Hi @mabahj,

I do not see this behaviour on my end, although I am running the latest master. Could you show this in animated form (e.g. gif or screen recording)?

**Comment by mabahj** [comment]
Here you go.

![CalendarExt2Jumping](https://user-images.githubusercontent.com/11989549/83800260-76235e00-a6a7-11ea-9e6e-6784f6a1bce6.gif)

**Comment by klaernie** [comment]
@mabahj That's really crazy behaviour.

As I couldn't see the behaviour with my config, but yours I decided to add breakpoints in the sources tab until I found a place it frequently visited - turns out, that you have this in your config:
```js
updateInterval: "10*60*1000", // 10 minutter¬
rotateInterval: "60*60*1000", // 1 hour. Trial to force the calender to update first day shown.¬
```

The `updateInterval` gets passed verbatim to javascripts `setTimeout()` function, which expects an integer there.
Now let's try to parse that value to an integer:
```js
parseInt("10*60*1000")
-> 10
```

So you accidentially set the update interval to 10 milliseconds, and then even the quickest browser in the world can't keep up and remove the old divs before the next one gets added in.

The fix is easy: just remove the double quotes, that way the value stored in the config is no longer `"10*60*1000"` but `600000`, which is the 10 minutes you intended.

I have no idea why the problem got exposed by [these commits](https://github.com/MMM-CalendarExt2/MMM-CalendarExt2/compare/a2828f5821757b20de9f7d962579e23a2a59899c...2f786b7eacfd66cf19a42da517af79dab3263a28), but the explanation is easy enough.
